#!/bin/sh -e

CC=${CC:-cc}
CFLAGS="-g -fsanitize=address -fsanitize=undefined -fno-sanitize-recover -I deps"

SOURCES=$(find . -name '*.c' -or -name '*.h')

${CC} ${CFLAGS} -o .test "deps/munit/munit.c" "test.c"
./.test $@
