#!/bin/sh -e

CC=${CC:-cc}
CFLAGS="-g -Wall -pedantic -fsanitize=address -fsanitize=undefined -fno-sanitize-recover -I deps"

CMD="${CC} ${CFLAGS} -o .test munit.c deps/munit/munit.c"
echo $CMD
$CMD
./.test $@
